Enhancement: Custom FullCalendar Configuration for Widgets
saade/filament-fullcalendar pull request #130
Opened 2023-11-22 21:20 UTC by sitenzo

In this pull request, we're introducing a feature that allows you to customize the FullCalendar configuration on a per-widget basis.

### What's New?
You can now set a default configuration at the plugin level. However, if you need to make specific changes for a particular widget, you have the flexibility to do so.

### How to Customize Widget Configuration?
In your widget, implement the getConfig method.

```
public function getConfig(): array {
    return [
        // Your custom FullCalendar configuration settings go here
    ];
}
```

Set up the custom configuration for the widget within the getConfig method.

### Merging Configurations
Behind the scenes, both the default plugin configuration and the widget-specific configuration files are merged into one final configuration for the widget. This ensures that you have full control over how FullCalendar behaves for each widget.

We believe this enhancement will provide greater flexibility and customization options for your FullCalendar widgets.

2023-11-28 12:40 UTC, saade commented
Hey! Thanks for your contribution, i'll review it soon :)

2023-12-29 01:58 UTC, StaffCollab commented
Hello.
This is a very needed feature! 
I want to customize the hidden days and times per user to only show the available times to book sessions on a per-caregiver availability basis.

This would be wonderful.

~~~
    protected function getFooterWidgets(): array
    {
        return [
            CalendarWidget::make()
                ->config([
                    'hiddenDays' => $this->record->notAvailableDays,
                ]),
        ];
    }
~~~

2024-02-19 20:48 UTC, lukas-frey commented
Any news on this PR? :)

2024-03-01 17:25 UTC, GeoSot commented
@saade can we help, in order to merge this?

2024-03-01 17:57 UTC, saade requested changes
Hey! Sorry for the low support on this plugin. I have big improvements for it on my TODO but i'm busy in another project atm.

If someone could apply and test those changes and test i'll be happy to merge. Thanks!

2024-03-01 17:57 UTC, saade commented on resources/views/fullcalendar.blade.php
> +                config: @js($this->getFinalConfig()),
```suggestion
                config: @js($this->getConfig()),
```

2024-03-01 17:57 UTC, saade commented on src/Widgets/Concerns/InteractsWithConfig.php
> +trait InteractsWithConfig
```suggestion
trait CanBeConfigured
```

2024-03-01 17:57 UTC, saade commented on src/Widgets/Concerns/InteractsWithConfig.php
> +	public function getFinalConfig()
```suggestion
	public function config(): array
```

2024-03-01 17:57 UTC, saade commented on README.md
> +    public function getConfig(): array
```suggestion
    public function config(): array
```

2024-03-01 17:57 UTC, saade commented on src/Widgets/Concerns/InteractsWithConfig.php
> +		return self::mergeArraysRecursive($initConfig,$widgetConfig);
```suggestion
		return [];
```

2024-03-01 17:57 UTC, saade commented on src/Widgets/Concerns/InteractsWithConfig.php
> +	}
```suggestion
```

2024-03-01 17:57 UTC, saade commented on src/Widgets/Concerns/InteractsWithConfig.php
> +    }
```suggestion
    protected function getConfig(): array
    {
        return array_merge_recursive(
            FilamentFullCalendarPlugin::get()->getConfig(),
            $this->config(),
        );
    }
```

2024-03-01 17:57 UTC, saade commented on src/Widgets/FullCalendarWidget.php
> +    use Concerns\InteractsWithConfig;
```suggestion
    use Concerns\CanBeConfigured;
```

2024-03-01 17:57 UTC, saade commented on src/Widgets/FullCalendarWidget.php
> +	}
```suggestion
```

2024-03-01 18:39 UTC, GeoSot commented
I am not sure if any other than @sitenzo can edit this PR

2024-03-01 19:41 UTC, saade commented
I'll have a look later today 👍🏼

2024-03-02 10:31 UTC, sitenzo commented
I have committed all the changes you have reviewed.

2024-03-02 15:53 UTC, GeoSot commented
It will be great to have a test case too, if it is possible, as [array_merge_recursive](https://www.php.net/manual/en/function.array-merge-recursive.php), maybe is not the perfect solution here

2024-03-23 05:59 UTC, Sjoerd24 commented
Any news on this pull request? This option would be extremely useful for me :) I think with the suggestion of @GeoSot to bring back [mergeArraysRecursive](https://github.com/saade/filament-fullcalendar/pull/130/commits/536cf81eec33021ed7d467ced44178e76b4b6e48) the PR should be fine right? Looks good to my eye at least 👍

2024-03-26 17:00 UTC, saade approved these changes

2024-03-26 17:00 UTC, saade commented
Thanks!

2024-03-26 17:00 UTC, merged