First Pass at Filamentphp V3 support.
saade/filament-fullcalendar pull request #88
Opened 2023-06-14 21:33 UTC by tonypartridge

This will require a new branch since we cannot have a v2 and v3 version. 

this is a first pass at a read-only version. Will do more testing and implementation with creation/editing at some point too, but allows people to get off the ground.

2023-07-30 17:47 UTC, ana-lisboa commented
Any chance this could possibly be merged alongside the possibility to delete events?

2023-08-02 06:23 UTC, ziming requested changes

2023-08-02 06:23 UTC, ziming commented on src/FilamentFullCalendarServiceProvider.php
> +    public function packageRegistered(): void
```suggestion
    public function packageBooted(): void
```

Asset registration should go into the packageBooted method

See:

https://filamentphp.com/docs/3.x/support/plugins/build-a-panel-plugin

https://filamentphp.com/docs/3.x/support/plugins/build-a-standalone-plugin

2023-08-09 10:34 UTC, lam0819 commented
your version quite few things need to change

Here is my version of upgrade v3, I have using in my project now (as local package)
https://github.com/saade/filament-fullcalendar/pull/99

2023-08-09 16:44 UTC, saade commented
Hello friends.

Just released v3.0.0-beta1.

PLEASE READ CAREFULLY:

- This is a first-pass release for supporting v3.
- There WILL BE BRAKING CHANGES when the final v3.0.0 is released.
- The docs are not updated yet. But there are no braking changes for now.


Thanks for everyone who opened a PR for supporting v3. :yellow_heart:

2023-08-09 16:44 UTC, closed without merging